# Generated by Django 4.0 on 2024-11-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signuptbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('fnm', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.BigIntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
