# Generated by Django 4.2 on 2024-11-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nodetbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quert_title', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('node_image', models.FileField(upload_to='query_images')),
                ('node_desc', models.CharField(max_length=10)),
            ],
        ),
    ]
